var gulp = require('gulp'),
    gutil = require('gulp-util');

// ALL THE METHODS SND PLUGINS THAT COME WITH GULP WILL VE ASSIGNED TO THIS VARIABLE

// SO WE CAN USE THIS GULP VARIABLE TO ISSUE COMMANDS
// GULP WORKS BY ALLOWING YOU TO CREATE DIFFERENT TASKS (THINGS WE NEED TO GET DONE)
// AND WE CREATE A TASK BY USING THE TASK METHOD. SO SINCE WE PLACE ALL THE THE METHODS INTO THIS GULP VARIABLE WE
// TELL GULP TO USE THE TASK METHOD, AND CREATE A TASK, SAY FOR INSTANCE 'log' OR WHATEVER.

gulp.task('log', function() {
  gutil.log('Workflows are awesome');
});
